### ISSUE TITLE
Wrong type argument: stringp, nil

### ISSUE THREAD

**Issue by bsed** [neeasade/emacs.d#1]
Wrong type argument: stringp, nil
ad-handle-definition: ‘align-regexp’ got redefined                                                          |
Loading ns/elisp...                                                                                         |To ensure normal operation, you should investigate and remove the
Loading ns/nix...                                                                                           |cause of the error in your initialization file.  Start Emacs with
Loading ns/javascript...                                                                                    |the ‘--debug-init’ option to view a complete error backtrace.

**Comment by neeasade** [comment]
@bsed what version of emacs are you running with? I aim for 27.1 --- also can you run with `emacs --debug-init` and post the results here? thanks

**Comment by bsed** [comment]
➜ emacs --version
GNU Emacs 27.1.90
Copyright (C) 2020 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.


system : big sur 11.1
iterm2 
Debugger entered--Lisp error: (void-function font)
  (font)
  eval-buffer(#<buffer  *load*-10684> nil "/Users/kelvin/.emacs.d/lisp/trees/util.el" nil t)  ; Reading at buffe$
  load-with-code-conversion("/Users/kelvin/.emacs.d/lisp/trees/util.el" "/Users/kelvin/.emacs.d/lisp/trees/util.$
  load("~/.emacs.d/lisp/trees/util.el")
  (catch 'config-catch (load "~/.emacs.d/lisp/trees/util.el") (setq ns/enable-util-p t))
  (let ((config-name "util")) (message (concat "Loading ns/" config-name "...")) (catch 'config-catch (load "~/.$
  ns/util()
  (catch 'config-catch (ns/sanity) (ns/evil) (ns/interface) (ns/editing) (ns/shell) (ns/org) (ns/org-capture) (n$
  (let ((config-name "core")) (message (concat "Loading ns/" config-name "...")) (catch 'config-catch (ns/sanity$
  ns/core()
  (if (getenv "NS_EMACS_BATCH") (progn (ns/scripting) (message (pr-string (eval (read (getenv "NS_EMACS_BATCH"))$
  eval-buffer(#<buffer  *load*> nil "/Users/kelvin/.emacs.d/init.el" nil t)  ; Reading at buffer position 2819   
  load-with-code-conversion("/Users/kelvin/.emacs.d/init.el" "/Users/kelvin/.emacs.d/init.el" t t)
  load("/Users/kelvin/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1ffcba40fcd1>) #f(compiled-function () #<byt$
  command-line()
  normal-top-level()

**Comment by neeasade** [comment]
have you made any changes to util.el? the trace fails on a function call to `(font)` in there but I don't see any in [the file](https://github.com/neeasade/emacs.d/blob/master/lisp/trees/util.el)

**Comment by bsed** [comment]
I'm not right util.el Make any changes to the file. Maybe it's OSX

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("-" nil 0)
  split-string(nil "-" nil)
  s-split("-" nil)
  (let* ((parts-in (s-split "-" font)) (parts (if (< (length parts-in) 2) (s-split "-" (s-replace " " "-" font)) parts-in)) (family (first parts)) (size (string-to-number ($
  ns/parse-font(nil)
  (apply 'set-face-attribute face nil (ns/parse-font (get-resource "st.font")))
  (let ((face (car --dolist-tail--))) (apply 'set-face-attribute face nil (ns/parse-font (get-resource "st.font"))) (setq --dolist-tail-- (cdr --dolist-tail--)))
  (while --dolist-tail-- (let ((face (car --dolist-tail--))) (apply 'set-face-attribute face nil (ns/parse-font (get-resource "st.font"))) (setq --dolist-tail-- (cdr --doli$
  (let ((--dolist-tail-- faces)) (while --dolist-tail-- (let ((face (car --dolist-tail--))) (apply 'set-face-attribute face nil (ns/parse-font (get-resource "st.font"))) (s$
  ns/set-faces-monospace((markdown-code-face))
  (catch 'config-catch (progn (straight-use-package 'markdown-mode) (defvar use-package--warning46 #'(lambda (keyword err) (let ((msg ...)) (display-warning 'use-package ms$
  (let ((config-name "markdown")) (message (concat "Loading ns/" config-name "...")) (catch 'config-catch (progn (straight-use-package 'markdown-mode) (defvar use-package--$
  ns/markdown()
  (catch 'config-catch (ns/c) (ns/fennel) (ns/autohotkey) (ns/clojure) (ns/elisp) (ns/nix) (ns/javascript) (ns/typescript) (ns/markdown) (ns/powershell) (ns/python) (setq n$
  (let ((config-name "development")) (message (concat "Loading ns/" config-name "...")) (catch 'config-catch (ns/c) (ns/fennel) (ns/autohotkey) (ns/clojure) (ns/elisp) (ns/$
  ns/development()
  (if (getenv "NS_EMACS_BATCH") (progn (ns/scripting) (message (pr-string (eval (read (getenv "NS_EMACS_BATCH")))))) (ns/core) (ns/extra) (ns/development) (ns/communication$
  eval-buffer(#<buffer  *load*> nil "/Users/kelvin/.emacs.d/init.el" nil t)  ; Reading at buffer position 2821
  load-with-code-conversion("/Users/kelvin/.emacs.d/init.el" "/Users/kelvin/.emacs.d/init.el" t t)
  load("/Users/kelvin/.emacs.d/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1fecce8179c9>) #f(compiled-function () #<bytecode 0x1fecce8179e1>) t)
  command-line()
  normal-top-level()


I've brought it back. It's the same problem

**Comment by neeasade** [comment]
Thanks for the trace, I see now -- non of my fallback fonts are available on your computer -- I'll make a tweak to fallback to default when no fonts are found

**Comment by bsed** [comment]
I didn't see the modification of the default font in the recently submitted code

**Comment by neeasade** [comment]
ope, thanks -- just pushed https://github.com/neeasade/emacs.d/commit/a6de8fb6fdf433827a1055fd5f1075c2870ec8c5

**Comment by bsed** [comment]
Loading ns/python...
Loading ns/communication...
Loading ns/irc...
Loading ns/email...
Loading ns/staging...
Loading /Users/kelvin/.emacs.d/lisp/trees/staging.el (source)...done
For information about GNU Emacs and the GNU system, type C-h C-a.
bloat-global: enabled
Loading /Users/kelvin/.emacs.d/lisp/trees/style.el (source)...
list: Wrong type argument: font, unspecified

**Comment by bsed** [comment]
Loading ns/python...
Loading ns/communication...
Loading ns/irc...
Loading ns/email...
Loading ns/staging...
Loading /Users/kelvin/.emacs.d/lisp/trees/staging.el (source)...done
For information about GNU Emacs and the GNU system, type C-h C-a.
bloat-global: enabled
Loading /Users/kelvin/.emacs.d/lisp/trees/style.el (source)...
list: Wrong type argument: font, unspecified
Hey! you should be clocked into something. 1209455758957360326
(New file)
File mode specification error: (wrong-type-argument stringp nil)
Error running timer: (wrong-type-argument integer-or-marker-p nil)
Active processes exist; kill them and exit anyway? (y or n) n

**Comment by neeasade** [comment]
Added menlo as a fallback font to try, which the internet tells me should be included with big sur -- aside from that looks OK -- to clarify the message about being clocked into something: that's because my setup here encompasses how I use org, which prompts me to clock my time underneath a heading when I'm at a computer
